In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('customer_churn_dataset-training-master.csv')

In [5]:
df.shape

(440833, 12)

In [3]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [7]:
df.sample(5)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
10533,10542.0,36.0,Male,34.0,6.0,8.0,20.0,Premium,Annual,405.00,30.0,1.0
187392,192203.0,48.0,Male,47.0,5.0,2.0,15.0,Premium,Quarterly,504.00,20.0,0.0
269510,276624.0,44.0,Male,46.0,24.0,0.0,1.0,Standard,Annual,525.07,17.0,0.0
219498,225172.0,41.0,Male,57.0,30.0,7.0,9.0,Premium,Monthly,317.30,30.0,1.0
17017,17026.0,34.0,Male,53.0,27.0,10.0,3.0,Premium,Monthly,163.00,17.0,1.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [9]:
df.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [13]:
df['Subscription Type'].value_counts()

Subscription Type
Standard    149128
Premium     148678
Basic       143026
Name: count, dtype: int64

In [16]:
df['Support Calls'].value_counts()

Support Calls
0.0     69875
1.0     69476
2.0     66571
3.0     52729
4.0     38750
5.0     24918
10.0    23900
7.0     23870
9.0     23630
8.0     23559
6.0     23554
Name: count, dtype: int64

In [17]:
df['Usage Frequency'].value_counts()

Usage Frequency
11.0    15311
29.0    15284
20.0    15258
25.0    15237
30.0    15232
21.0    15205
19.0    15204
12.0    15179
26.0    15134
15.0    15129
27.0    15121
14.0    15094
10.0    15090
23.0    15072
17.0    15058
24.0    15038
13.0    15015
28.0    15012
22.0    15005
16.0    14949
18.0    14871
3.0     13843
1.0     13797
9.0     13770
6.0     13746
8.0     13725
5.0     13716
2.0     13633
7.0     13555
4.0     13549
Name: count, dtype: int64

In [14]:
df['Churn'].value_counts()

Churn
1.0    249999
0.0    190833
Name: count, dtype: int64

In [15]:
df['Gender'].value_counts()

Gender
Male      250252
Female    190580
Name: count, dtype: int64

In [12]:
df['Age'].value_counts()

Age
50.0    13527
42.0    12578
40.0    12417
48.0    12379
47.0    12369
46.0    12368
44.0    12344
49.0    12331
41.0    12314
43.0    12298
45.0    12265
38.0    11181
31.0    11092
35.0    11062
36.0    11031
37.0    11024
33.0    10990
39.0    10961
30.0    10907
32.0    10885
34.0    10829
26.0     9692
25.0     9647
22.0     9639
28.0     9608
21.0     9574
29.0     9571
20.0     9553
23.0     9513
27.0     9472
24.0     9465
18.0     8219
19.0     8073
59.0     5573
63.0     5560
64.0     5496
55.0     5489
56.0     5477
54.0     5472
53.0     5467
65.0     5460
51.0     5437
60.0     5430
61.0     5407
58.0     5373
52.0     5364
57.0     5361
62.0     5288
Name: count, dtype: int64